### ISSUE TITLE
Add JMD to currency option to movemoney screen

### ISSUE THREAD

**Issue by islandbitcoin** [lnflash/flash-mobile#6]
Currently only USD and BTC options, want to add JMD as an option. Potential display modes:

- JMD display, pegged to JMD rate || USD display, pegged to USD rate || BTC display pegged to BTC rate

- JMD display, pegged to USD exchange rate  || USD display, pegged to USD rate || BTC display pegged to BTC rate

- JMD display, pegged to BTC exchange rate  || USD display, pegged to USD rate || BTC display pegged to BTC rate

**Comment by islandbitcoin** [comment]
An upcoming update to the galoy backend will have multiple currencies enabled. May make sense to wait on this update and merge.

**Comment by Ayush0054** [comment]
hello Ayush there, almost 3 week ago  we have a chat on mattermost galoy server about bounties on making components for inflash payement app https://github.com/lnflash/flash-mobile , now after two weeks i have made a contribution in galoy   mobile  https://github.com/GaloyMoney/galoy-mobile/pull/1172   and now i have got  enough confidence to make some components for your app . since you were not active on galoy server . thats why  im commenting here.

**Comment by islandbitcoin** [comment]
handled by galoy-mobile
