### ISSUE TITLE
New User should be auto generated a npub and a nsec for their nostr profile and nsec should be saved to the local secure storage, just like the seed phrase

### ISSUE THREAD

**Issue by Nodirbek75** [lnflash/flash-mobile#62]

**Comment by abhay-raizada** [comment]
Just want to know if i have the the scope of this issue right:

1.  Nostr private key should be generated on mount of the homescreen, if it is not already present in the Keychain (similar to seed phrase).
2. There should be an option on the settings screen to see the users nsec, should this be a modal with the nsec and a copy button? or a seperate screen? 
<img width="365" alt="image" src="https://github.com/lnflash/flash-mobile/assets/8532031/e489d391-976d-401a-9038-42f7d956a814">

**Comment by islandbitcoin** [comment]
> 2. There should be an option on the settings screen to see the users nsec, should this be a modal with the nsec and a copy button? or a seperate screen?
> 

Whatever gives the user the cleanest UX. I would assume a modal?

**Comment by abhay-raizada** [comment]
from discord: 

![image](https://github.com/lnflash/flash-mobile/assets/8532031/f5745e4f-dd8d-4174-9ba3-eed21e41b891) 

feedback from @islandbitcoin :
 - would be good to put this in the github issues (or PR) conversation so we keep everything in one place
Overall UI theme is good
 - This is showing the private key, not the nostr address (npub). i think we should give it a better label, like "nostr secret key"
- I think we should use the "password" field to show this, so it shows up as * with the copy button (and a icon on the right to show it if they want).

Bonus work: should we show the npub? how can the user see their npub otherwise? I dont think we have a plan for that yet.

**Comment by abhay-raizada** [comment]
@Nodirbek75  made it similar to the "set staging url"  modal also incorporated the feedback in the new design:

<img width="381" alt="image" src="https://github.com/lnflash/flash-mobile/assets/8532031/1055dfc0-37c9-4a80-815e-6ae542e312e1">
